# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

map_impl <- function(env, x_name, f_name) {
    .Call('_purrr_map_impl', PACKAGE = 'purrr', env, x_name, f_name)
}

vmap_impl <- function(env, x_name, f_name, type) {
    .Call('_purrr_vmap_impl', PACKAGE = 'purrr', env, x_name, f_name, type)
}

map2_impl <- function(env, x_name, y_name, f_name) {
    .Call('_purrr_map2_impl', PACKAGE = 'purrr', env, x_name, y_name, f_name)
}

